FROM frolvlad/alpine-glibc

RUN apk upgrade && apk add curl

ADD ./envoy /
RUN chmod u+x /envoy

ADD ./nxgw-envoy-zipkin.yaml /etc/


CMD /envoy --v2-config-only -l info -c /etc/nxgw-envoy-zipkin.yaml --enable-mutex-tracing --service-cluster nxgw
