FROM frolvlad/alpine-glibc

RUN apk upgrade && apk add curl

ADD ./envoy /
RUN chmod u+x /envoy

ADD ./front-envoy-zipkin.yaml /etc/


CMD /envoy --v2-config-only -l info -c /etc/front-envoy-zipkin.yaml --service-cluster front-proxy
