version: '3'
services:

  front-envoy:
    build:
      context: ./
      dockerfile: Dockerfile-frontenvoy
    networks:
      - envoymesh
    expose:
      - "80"
      - "9901"
    ports:
      - "8000:80"
      - "9901:9901"

  servicea:
    build:
      context: ./
      dockerfile: Dockerfile-serviceA
    networks:
      envoymesh:
        aliases:
          - servicea
    environment:
      - SERVICE_NAME=A
    expose:
      - "80"

  serviceb:
    build:
      context: ./
      dockerfile: Dockerfile-serviceB
    networks:
      envoymesh:
        aliases:
          - serviceb
    environment:
      - SERVICE_NAME=B
    expose:
      - "80"
  servicec:
    build:
      context: ./
      dockerfile: Dockerfile-serviceC
    networks:
      envoymesh:
        aliases:
          - servicec
    environment:
      - SERVICE_NAME=C
    expose:
      - "80"
  serviced:
    build:
      context: ./
      dockerfile: Dockerfile-serviceD
    networks:
      envoymesh:
        aliases:
          - serviced
    environment:
      - SERVICE_NAME=D
    expose:
      - "80"
  zipkin:
    image: openzipkin/zipkin
    networks:
      envoymesh:
        aliases:
          - zipkin
    expose:
      - "9411"
    ports:
      - "9411:9411"
networks:
  envoymesh: {}
